londiste/handlers/dispatch: fixed issue with missing part_func description
Fixes the following issue with Dispatcher based handlers:
ValueError: Invalid handler argument: ['part_func']